-- --------------------------------------------------------
-- Servidor:                     fn01
-- Versão do servidor:           10.11.2-MariaDB - mariadb.org binary distribution
-- OS do Servidor:               Win64
-- HeidiSQL Versão:              12.3.0.6589
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Copiando estrutura do banco de dados para teste_grupo_mbs
CREATE DATABASE IF NOT EXISTS `teste_grupo_mbs` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_swedish_ci */;
USE `teste_grupo_mbs`;

-- Copiando estrutura para tabela teste_grupo_mbs.contador
CREATE TABLE IF NOT EXISTS `contador` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PESSOA` int(11) NOT NULL,
  `INSCRICAO_CRC` varchar(15) DEFAULT NULL,
  `FONE` varchar(14) DEFAULT NULL,
  `FAX` varchar(50) DEFAULT NULL,
  `LOGRADOURO` varchar(100) DEFAULT NULL,
  `NUMERO` varchar(10) DEFAULT NULL,
  `COMPLEMENTO` varchar(100) DEFAULT NULL,
  `BAIRRO` varchar(60) DEFAULT NULL,
  `CEP` varchar(8) DEFAULT NULL,
  `MUNICIPIO_IBGE` bigint(11) DEFAULT NULL,
  `UF` char(2) DEFAULT NULL,
  `EMAIL` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PESSOA_CONTADOR` (`ID_PESSOA`),
  CONSTRAINT `fk_{55588BE2-A33F-4E0C-9E20-81503D174305}` FOREIGN KEY (`ID_PESSOA`) REFERENCES `pessoa` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_swedish_ci PACK_KEYS=0 COMMENT='Armazena os dados do contador da empresa. ';

-- Copiando dados para a tabela teste_grupo_mbs.contador: ~2 rows (aproximadamente)
INSERT INTO `contador` (`ID`, `ID_PESSOA`, `INSCRICAO_CRC`, `FONE`, `FAX`, `LOGRADOURO`, `NUMERO`, `COMPLEMENTO`, `BAIRRO`, `CEP`, `MUNICIPIO_IBGE`, `UF`, `EMAIL`) VALUES
	(1, 662, '000000', '000000000000', '00000000000000', '666000000', '6660000000', '6660000000000000000', '0000000000666', '66600000', 66600000000, 'AP', '0000000000000000000'),
	(2, 665, '131323123', '1233123123', '123213', '31312', '123', '12313131', '213213', '131', 23112, '', '123123'),
	(5, 673, '345345', '435435', '43534', '', '', '', '', '', NULL, '', '4534535');

-- Copiando estrutura para tabela teste_grupo_mbs.empresa
CREATE TABLE IF NOT EXISTS `empresa` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_RESPONSAVEL_SOCIO` int(11) NOT NULL,
  `ID_MATRIZ` int(11) NOT NULL,
  `ID_SINDICATO_PATRONAL` int(11) DEFAULT NULL,
  `ID_FPAS` int(11) DEFAULT NULL,
  `ID_CONTADOR` int(11) DEFAULT NULL,
  `RAZAO_SOCIAL` varchar(150) DEFAULT NULL,
  `NOME_FANTASIA` varchar(150) DEFAULT NULL,
  `CNPJ` varchar(14) DEFAULT NULL,
  `INSCRICAO_ESTADUAL` varchar(30) DEFAULT NULL,
  `INSCRICAO_ESTADUAL_ST` varchar(30) DEFAULT NULL,
  `INSCRICAO_MUNICIPAL` varchar(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `INSCRICAO_JUNTA_COMERCIAL` varchar(30) DEFAULT NULL,
  `DATA_INSC_JUNTA_COMERCIAL` date DEFAULT NULL,
  `TIPO` char(1) DEFAULT NULL COMMENT 'Valores possíveis: M-Matriz | F-Filial | D=Depósito',
  `DATA_CADASTRO` date DEFAULT NULL,
  `DATA_INICIO_ATIVIDADES` date DEFAULT NULL,
  `SUFRAMA` varchar(9) DEFAULT NULL,
  `EMAIL` varchar(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `IMAGEM_LOGOTIPO` varchar(2000) DEFAULT NULL,
  `CRT` char(1) DEFAULT NULL COMMENT 'Código Regime Tributário [1=Simples Nacional | 2=Simples Nacional - excesso de sublimite da receita bruta  | 3=Regime Normal ',
  `TIPO_REGIME` char(1) DEFAULT NULL COMMENT '1-Lucro REAL;2-Lucro presumido;3-Simples nacional;',
  `ALIQUOTA_PIS` decimal(18,6) DEFAULT NULL COMMENT 'Aliquota do PIS padrao para a empresa',
  `CONTATO` varchar(50) DEFAULT NULL COMMENT 'Aliquota padrao do Confins',
  `ALIQUOTA_COFINS` decimal(18,6) DEFAULT NULL,
  `CODIGO_IBGE_CIDADE` int(11) DEFAULT NULL,
  `CODIGO_IBGE_UF` int(11) DEFAULT NULL,
  `CODIGO_TERCEIROS` decimal(18,6) DEFAULT NULL COMMENT 'Codigo das contribuicoes para terceiros incidentes sobre a folha de pagamento (os terceiros sao SESI, SENAI, SEBRAE, INCRA, etc) esta tabela consta na IN 971/2009  da RFB',
  `CODIGO_GPS` int(11) DEFAULT NULL COMMENT 'Codigo de pagamento da GPS, trata-se de tabale encontrada no site da Previdencia Social',
  `ALIQUOTA_SAT` decimal(18,6) DEFAULT NULL COMMENT 'Aliquota do Seguro contra Acidente de trabalho incidente sobre a folha de pagametno dos empregados',
  PRIMARY KEY (`ID`),
  KEY `FK_CONTADOR_EMPRESA` (`ID_CONTADOR`),
  KEY `FK_RESPONSAVEL_SOCIO_EMPRESA` (`ID_RESPONSAVEL_SOCIO`),
  KEY `FK_FPAS_EMPRESA` (`ID_FPAS`),
  KEY `FK_SINDICATO_EMPRESA` (`ID_SINDICATO_PATRONAL`),
  KEY `FK_MATRIZ_EMPRESA` (`ID_MATRIZ`)
) ENGINE=InnoDB AUTO_INCREMENT=40 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_swedish_ci PACK_KEYS=0 COMMENT='Tabela com as empresas que utilizam o sistema. ERP multi-empresa.';

-- Copiando dados para a tabela teste_grupo_mbs.empresa: ~32 rows (aproximadamente)
INSERT INTO `empresa` (`ID`, `ID_RESPONSAVEL_SOCIO`, `ID_MATRIZ`, `ID_SINDICATO_PATRONAL`, `ID_FPAS`, `ID_CONTADOR`, `RAZAO_SOCIAL`, `NOME_FANTASIA`, `CNPJ`, `INSCRICAO_ESTADUAL`, `INSCRICAO_ESTADUAL_ST`, `INSCRICAO_MUNICIPAL`, `INSCRICAO_JUNTA_COMERCIAL`, `DATA_INSC_JUNTA_COMERCIAL`, `TIPO`, `DATA_CADASTRO`, `DATA_INICIO_ATIVIDADES`, `SUFRAMA`, `EMAIL`, `IMAGEM_LOGOTIPO`, `CRT`, `TIPO_REGIME`, `ALIQUOTA_PIS`, `CONTATO`, `ALIQUOTA_COFINS`, `CODIGO_IBGE_CIDADE`, `CODIGO_IBGE_UF`, `CODIGO_TERCEIROS`, `CODIGO_GPS`, `ALIQUOTA_SAT`) VALUES
	(1, 1, 1, 1, 1, 1, 'MBS RASTER LTDA', 'MBS RASTREAMENTO', '12345678000190', '12345678', NULL, NULL, '12345678', '2024-05-13', 'M', '2024-05-13', '2024-05-12', NULL, 'contato@mbsraster.com.br', NULL, '1', '3', NULL, '11987654321', NULL, NULL, NULL, NULL, NULL, NULL),
	(2, 2, 1, 1, 1, 1, 'Tech Solutions LTDA', 'TechSol', '23456789000101', '23456789', NULL, NULL, '23456789', '2024-06-06', 'M', '2024-06-06', '2024-06-06', NULL, 'contato@techsol.com.br', NULL, '1', '3', NULL, '11987654322', NULL, NULL, NULL, NULL, NULL, NULL),
	(3, 1, 1, NULL, NULL, NULL, 'MBS RASTER', 'MBS RASTREAMENTO', '12345678000190', NULL, NULL, NULL, NULL, '2024-05-13', 'M', '2024-05-13', '2024-05-12', NULL, NULL, NULL, '1', '3', NULL, '11987654321', NULL, NULL, NULL, NULL, NULL, NULL),
	(4, 1, 1, NULL, NULL, NULL, 'Tech Solutions LTDA', 'TechSol', '12345678000190', NULL, NULL, NULL, NULL, '2024-06-06', 'M', '2024-06-06', '2024-06-06', NULL, 'contato@techsol.com.br', NULL, '1', '3', NULL, '11987654321', NULL, NULL, NULL, NULL, NULL, NULL),
	(5, 1, 1, NULL, NULL, NULL, 'Inova Tecnologia', 'InovaTec', '98765432000145', NULL, NULL, NULL, NULL, '2024-07-01', 'M', '2024-07-01', '2024-07-01', NULL, 'contato@inovatec.com.br', NULL, '1', '3', NULL, '11987654322', NULL, NULL, NULL, NULL, NULL, NULL),
	(6, 1, 1, NULL, NULL, NULL, 'Global Trade', 'GlobalT', '12398765432100', NULL, NULL, NULL, NULL, '2024-07-10', 'M', '2024-07-10', '2024-07-10', NULL, 'contato@globaltrade.com', NULL, '1', '3', NULL, '11987654323', NULL, NULL, NULL, NULL, NULL, NULL),
	(7, 1, 1, NULL, NULL, NULL, 'Construtora ABC', 'Construtora ABC', '32165498700011', NULL, NULL, NULL, NULL, '2024-08-01', 'M', '2024-08-01', '2024-08-01', NULL, 'contato@construtoraabc.com.br', NULL, '1', '3', NULL, '11987654324', NULL, NULL, NULL, NULL, NULL, NULL),
	(8, 1, 1, NULL, NULL, NULL, 'Agropecuária São Jorge', 'Agro São Jorge', '65432178900023', NULL, NULL, NULL, NULL, '2024-08-15', 'M', '2024-08-15', '2024-08-15', NULL, 'contato@agrosaojorge.com.br', NULL, '1', '3', NULL, '11987654325', NULL, NULL, NULL, NULL, NULL, NULL),
	(9, 1, 1, NULL, NULL, NULL, 'Educação Integral', 'EduIntegral', '98712345600033', NULL, NULL, NULL, NULL, '2024-09-05', 'M', '2024-09-05', '2024-09-05', NULL, 'contato@eduintegral.com.br', NULL, '1', '3', NULL, '11987654326', NULL, NULL, NULL, NULL, NULL, NULL),
	(10, 1, 1, NULL, NULL, NULL, 'Consultoria Financeira', 'FinanConsult', '32198765400044', NULL, NULL, NULL, NULL, '2024-09-10', 'M', '2024-09-10', '2024-09-10', NULL, 'contato@financonsult.com.br', NULL, '1', '3', NULL, '11987654327', NULL, NULL, NULL, NULL, NULL, NULL),
	(11, 1, 1, NULL, NULL, NULL, 'Marketing Digital', 'MktDigital', '12345678900055', NULL, NULL, NULL, NULL, '2024-09-20', 'M', '2024-09-20', '2024-09-20', NULL, 'contato@mktdigital.com.br', NULL, '1', '3', NULL, '11987654328', NULL, NULL, NULL, NULL, NULL, NULL),
	(12, 1, 1, NULL, NULL, NULL, 'Logística Moderna', 'LogisticaMod', '98765432100066', NULL, NULL, NULL, NULL, '2024-09-25', 'M', '2024-09-25', '2024-09-25', NULL, 'contato@logisticamod.com.br', NULL, '1', '3', NULL, '11987654329', NULL, NULL, NULL, NULL, NULL, NULL),
	(15, 1, 1, 1, 1, 1, 'MBS RASTER LTDA', 'MBS RASTREAMENTO', '12345678000190', '12345678', NULL, '12345678', '12345678', '2024-05-13', 'M', '2024-05-13', '2024-05-12', NULL, 'contato@mbsraster.com.br', NULL, '1', '3', NULL, '11987654321', NULL, NULL, NULL, NULL, NULL, NULL),
	(16, 1, 1, 1, 1, 1, 'MBS RASTER LTDA', 'MBS RASTREAMENTO', '12345678000190', '12345678', NULL, '12345678', '12345678', '2024-05-13', 'M', '2024-05-13', '2024-05-12', NULL, 'contato@mbsraster.com.br', NULL, '1', '3', NULL, '11987654321', NULL, NULL, NULL, NULL, NULL, NULL),
	(17, 1, 1, 1, 1, 1, 'MBS RASTER LTDA', 'MBS RASTREAMENTO', '12345678000190', '12345678', NULL, '12345678', '12345678', '2024-05-13', 'M', '2024-05-13', '2024-05-12', NULL, 'contato@mbsraster.com.br', NULL, '1', '3', NULL, '11987654321', NULL, NULL, NULL, NULL, NULL, NULL),
	(18, 1, 1, 1, 1, 1, 'MBS RASTER LTDA', 'MBS RASTREAMENTO', '12345678000190', '12345678', NULL, '12345678', '12345678', '2024-05-13', 'M', '2024-05-13', '2024-05-12', NULL, 'contato@mbsraster.com.br', NULL, '1', '3', NULL, '11987654321', NULL, NULL, NULL, NULL, NULL, NULL),
	(19, 1, 1, 1, 1, 1, 'MBS RASTER LTDA', 'MBS RASTREAMENTO', '12345678000190', '12345678', NULL, '12345678', '12345678', '2024-05-13', 'M', '2024-05-13', '2024-05-12', NULL, 'contato@mbsraster.com.br', NULL, '1', '3', NULL, '11987654321', NULL, NULL, NULL, NULL, NULL, NULL),
	(20, 1, 1, 1, 1, 1, 'MBS RASTER LTDA', 'MBS RASTREAMENTO', '12345678000190', '12345678', NULL, '12345678', '12345678', '2024-05-13', 'M', '2024-05-13', '2024-05-12', NULL, 'contato@mbsraster.com.br', NULL, '1', '3', NULL, '11987654321', NULL, NULL, NULL, NULL, NULL, NULL),
	(26, 1, 1, 1, 1, 1, 'MBS RASTER LTDA', 'MBS RASTREAMENTO', '12345678000190', '12345678', NULL, '12345678', '12345678', '2024-05-13', 'M', '2024-05-13', '2024-05-12', NULL, 'contato@mbsraster.com.br', NULL, '1', '3', NULL, '11987654321', NULL, NULL, NULL, NULL, NULL, NULL),
	(27, 1, 1, 1, 1, 1, 'MBS RASTER LTDA', 'MBS RASTREAMENTO', '12345678000190', '12345678', NULL, '12345678', '12345678', '2024-05-13', 'M', '2024-05-13', '2024-05-12', NULL, 'contato@mbsraster.com.br', NULL, '1', '3', NULL, '11987654321', NULL, NULL, NULL, NULL, NULL, NULL),
	(28, 1, 1, 1, 1, 1, 'MBS RASTER LTDA', 'MBS RASTREAMENTO', '12345678000190', '12345678', NULL, '12345678', '12345678', '2024-05-13', 'M', '2024-05-13', '2024-05-12', NULL, 'contato@mbsraster.com.br', NULL, '1', '3', NULL, '11987654321', NULL, NULL, NULL, NULL, NULL, NULL),
	(29, 1, 1, 1, 1, 1, 'MBS RASTER LTDA', 'MBS RASTREAMENTO', '12345678000190', '12345678', NULL, '12345678', '12345678', '2024-05-13', 'M', '2024-05-13', '2024-05-12', NULL, 'contato@mbsraster.com.br', NULL, '1', '3', NULL, '11987654321', NULL, NULL, NULL, NULL, NULL, NULL),
	(30, 1, 1, 1, 1, 1, 'MBS RASTER LTDA', 'MBS RASTREAMENTO', '12345678000190', '12345678', NULL, '12345678', '12345678', '2024-05-13', 'M', '2024-05-13', '2024-05-12', NULL, 'contato@mbsraster.com.br', NULL, '1', '3', NULL, '11987654321', NULL, NULL, NULL, NULL, NULL, NULL),
	(31, 1, 1, 1, 1, 1, 'MBS RASTER LTDA', 'MBS RASTREAMENTO', '12345678000190', '12345678', NULL, '12345678', '12345678', '2024-05-13', 'M', '2024-05-13', '2024-05-12', NULL, 'contato@mbsraster.com.br', NULL, '1', '3', NULL, '11987654321', NULL, NULL, NULL, NULL, NULL, NULL),
	(32, 1, 1, 1, 1, 1, 'MBS RASTER LTDA', 'MBS RASTREAMENTO', '12345678000190', '12345678', NULL, '12345678', '12345678', '2024-05-13', 'M', '2024-05-13', '2024-05-12', NULL, 'contato@mbsraster.com.br', NULL, '1', '3', NULL, '11987654321', NULL, NULL, NULL, NULL, NULL, NULL),
	(33, 1, 1, 1, 1, 1, 'MBS RASTER LTDA', 'MBS RASTREAMENTO', '12345678000190', '12345678', NULL, '12345678', '12345678', '2024-05-13', 'M', '2024-05-13', '2024-05-12', NULL, 'contato@mbsraster.com.br', NULL, '1', '3', NULL, '11987654321', NULL, NULL, NULL, NULL, NULL, NULL),
	(34, 1, 1, 1, 1, 1, 'MBS RASTER LTDA', 'MBS RASTREAMENTO', '12345678000190', '12345678', NULL, '12345678', '12345678', '2024-05-13', 'M', '2024-05-13', '2024-05-12', NULL, 'contato@mbsraster.com.br', NULL, '1', '3', NULL, '11987654321', NULL, NULL, NULL, NULL, NULL, NULL),
	(35, 1, 1, 1, 1, 1, 'MBS RASTER LTDA', 'MBS RASTREAMENTO', '12345678000190', '12345678', NULL, '12345678', '12345678', '2024-05-13', 'M', '2024-05-13', '2024-05-12', NULL, 'contato@mbsraster.com.br', NULL, '1', '3', NULL, '11987654321', NULL, NULL, NULL, NULL, NULL, NULL),
	(36, 1, 1, 1, 1, 1, 'MBS RASTER LTDA', 'MBS RASTREAMENTO', '12345678000190', '12345678', NULL, '12345678', '12345678', '2024-05-13', 'M', '2024-05-13', '2024-05-12', NULL, 'contato@mbsraster.com.br', NULL, '1', '3', NULL, '11987654321', NULL, NULL, NULL, NULL, NULL, NULL),
	(37, 1, 1, 1, 1, 1, 'MBS RASTER LTDA', 'MBS RASTREAMENTO', '12345678000190', '12345678', NULL, '12345678', '12345678', '2024-05-13', 'M', '2024-05-13', '2024-05-12', NULL, 'contato@mbsraster.com.br', NULL, '1', '3', NULL, '11987654321', NULL, NULL, NULL, NULL, NULL, NULL),
	(38, 213, 2, 2, 2, 2, 'Ricardo Tecnologias 33', 'RicardoTecno', '12313213987921', '353543', '4534534', '453', '4534354343', '2024-10-01', 'M', '2024-10-01', '2024-10-01', '123213', 'marcioTec@hotmailcom', 'lockdaaws', '1', '3', 32123312.000000, '12313123213', 123112313123.000000, 1231323, 123, 2312313.000000, 123, 123131312.000000),
	(39, 1, 1, 1, 1, 1, 'JoãoTech', 'Jão do frilas', '97924574000199', '654321987', '123456789012', '9876543210', '1234567890', '2024-10-02', 'M', '2024-12-31', '2024-10-02', '456789123', 'contato@jaodofrilas.com', 'https://example.com/logotipos/joao_do_frilas.png', '1', '1', 165.000000, '11987654321', NULL, 1234567, 12, 890123456.000000, 234567, NULL);

-- Copiando estrutura para tabela teste_grupo_mbs.fpas
CREATE TABLE IF NOT EXISTS `fpas` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODIGO` int(11) DEFAULT NULL,
  `CNAE` varchar(14) DEFAULT NULL,
  `ALIQUOTA_SAT` decimal(10,0) DEFAULT NULL,
  `DESCRICAO` varchar(250) DEFAULT NULL,
  `PERCENTUAL_INSS_PATRONAL` decimal(18,6) DEFAULT NULL,
  `CODIGO_TERCEIRO` decimal(4,0) DEFAULT NULL,
  `PERCENTUAL_TERCEIROS` decimal(18,6) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_swedish_ci PACK_KEYS=0;

-- Copiando dados para a tabela teste_grupo_mbs.fpas: ~0 rows (aproximadamente)
INSERT INTO `fpas` (`ID`, `CODIGO`, `CNAE`, `ALIQUOTA_SAT`, `DESCRICAO`, `PERCENTUAL_INSS_PATRONAL`, `CODIGO_TERCEIRO`, `PERCENTUAL_TERCEIROS`) VALUES
	(1, 1231, '123123', 4, '313213', 312.543000, 123, 31.230000);

-- Copiando estrutura para tabela teste_grupo_mbs.matriz
CREATE TABLE IF NOT EXISTS `matriz` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `RAZAO_SOCIAL` varchar(150) DEFAULT NULL,
  `CNPJ` varchar(14) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_swedish_ci PACK_KEYS=0;

-- Copiando dados para a tabela teste_grupo_mbs.matriz: ~0 rows (aproximadamente)
INSERT INTO `matriz` (`ID`, `RAZAO_SOCIAL`, `CNPJ`) VALUES
	(1, 'Gourmet Foods Comércio de Alimentos Eireli', '78901234000157');

-- Copiando estrutura para tabela teste_grupo_mbs.pessoa
CREATE TABLE IF NOT EXISTS `pessoa` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(150) NOT NULL,
  `TIPO` char(1) NOT NULL COMMENT 'F=Física | J=Jurídica',
  `EMAIL` varchar(250) DEFAULT NULL,
  `SITE` varchar(250) DEFAULT NULL,
  `CLIENTE` char(1) DEFAULT 'N' COMMENT 'S=Sim | N=Não',
  `FORNECEDOR` char(1) DEFAULT 'N' COMMENT 'S=Sim | N=Não',
  `COLABORADOR` char(1) DEFAULT 'N' COMMENT 'S=Sim | N=Não',
  `CONVENIO` char(1) DEFAULT 'N' COMMENT 'S=Sim | N=Não',
  `CONTADOR` char(1) DEFAULT 'N' COMMENT 'S=Sim | N=Não',
  `TRANSPORTADORA` char(1) DEFAULT 'N' COMMENT 'S=Sim | N=Não',
  `TERCEIRO` char(1) DEFAULT 'N' COMMENT 'S=Sim | N=Não',
  `SOCIO` char(1) DEFAULT 'N' COMMENT 'S=Sim | N=Não',
  `TMP` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=677 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_swedish_ci PACK_KEYS=0 COMMENT='Tabela que armazena os dados da PESSOA. Demais tabelas devem especializar esta tabela com seus próprios dados: FORNECEDOR, TRANSPORTADORA, CLIENTE, etc.';

-- Copiando dados para a tabela teste_grupo_mbs.pessoa: ~642 rows (aproximadamente)
INSERT INTO `pessoa` (`ID`, `NOME`, `TIPO`, `EMAIL`, `SITE`, `CLIENTE`, `FORNECEDOR`, `COLABORADOR`, `CONVENIO`, `CONTADOR`, `TRANSPORTADORA`, `TERCEIRO`, `SOCIO`, `TMP`) VALUES
	(1, 'MARCIO ADRIANO BAPTISTA DE SOUZA', 'F', '', 'WWW.MBSRASTREADORES.COM.BR', '', '', 'S', '', '', '', '', '', NULL),
	(14, 'M&M Soluções agricolas ', 'J', '', '', 'S', '', '', '', '', '', '', '', NULL),
	(15, 'Tratornaves', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(16, 'A. C. FERREIRA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(17, 'ADEMILSON TADEI DOS SANTOS ME.', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(18, 'ADONIAS PEREIRA CHAVES', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(19, 'AGRO REVELLES', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(20, 'AGROPECUARIA FRANZONI', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(21, 'ALESSANDRO IORI', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(22, 'ANA ELYSA SPOLAOR DA MATA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(23, 'ANDRE LUIZ PITON', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(24, 'ANTÔNIO CARLOS LOURENCO DA COSTA ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(25, '	ARNALDO LUIZ NOGUEIRA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(26, 'ARTHUR HENRIQUE SCHULTZ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(27, 'AUTO ELETRICA PATRICK', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(28, 'BERTACO MOVEIS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(29, 'BRUNO BAPTISTA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(30, 'BRUNO DA SILVA GORITA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(31, 'CALUAH COMERCIAL LTDA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(32, 'CLAUDIA BAPTISTA DE ALMEIDA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(33, 'CONCRETIZE', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(34, 'DONIZETI MARINHO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(35, 'DOUGLAS DE PAULA E SILVA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(36, 'EDVALDO ADRIANO ARAÚJO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(37, 'ELIANA INÁCIO DOS SANTOS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(38, 'FABIO PERES BAPTISTA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(39, 'FAZENDA DOIS IRMAOS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(40, 'FLÁVIO EDUARDO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(41, 'FORTE MAQUINAS AMBIENTAL', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(42, 'FRANCISCO CARVALHO TRINDADE', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(43, 'GARIBALDI MACHADO LEOPOLDINO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(44, 'GRAN PEL ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(45, '	GUILHERME ALVES DE SOUZA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(46, 'HELITON LUIZ DE MATOS ELASTICO ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(47, '	ITAMAR TEIXEIRA MOREIRA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(48, '	IVÃ DE OLIVEIRA DA MATTA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(49, '	JACOB SALVIANO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(50, 'JEFERSON C TEIXEIRA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(52, 'TESTE 51 ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(53, 'TESTE 53', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(54, 'JK NOVO HORIZONTE EMPR.IMOBILIÁRIOS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(55, 'JOÃO DONIZETE CHRISTIANO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(56, '	JOAO PAULO DE ALMEIDA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(57, '	JOAO VICTOR OGLIARI RAMALHO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(58, 'JOSÉ JORGE DE OLIVEIRA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(59, 'JVDC SERVIÇOS AGRÍCOLAS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(60, 'LAGO E SOL', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(61, 'LEANDRO AUGUSTO FAGUNDES', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(62, 'LIDIO BOGAS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(63, '	LINDON FELISBERTO DA SILVA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(64, '	LUCIO MAGRI', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(65, 'LUIS FERNANDO PACCO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(67, 'MANOEL CARLOS CHRISTIANO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(68, '	MARCELINO DA COSTA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(69, 'MARCELO GRATAO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(70, 'MARCOS ALEXANDRE', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(71, 'Marcos Henrique de Sousa', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(72, 'MARIA EDUARDA DA SILVEIRA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(73, 'MBS LOGISTICA E TRANSPORTE ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(74, 'NILTON', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(75, 'OSVALDO BISPO NETO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(76, '	PAULO CEZAR CARETA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(77, '	PAULO COELHO FRUCTUOSO DE LIMA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(78, 'PAULO DE TARCIO MARTIN', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(79, '	PEDRO PAULO DA SILVA ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(80, '	PREFEITURA MUNICIPAL DE NOVA GRANADA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(81, '	R.R.C TRANSPORTES E LOGÍSTICA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(82, 'RAIMUNDO SANTOS DA FONSECA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(83, 'RAUL GARCIA DA SILVA ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(84, 'REGINALDO IORI', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(86, '	REGINALDO MANHOSO ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(87, 'REGINALDO MARTINS PRIMOS ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(88, '	RICARDO ALMEIDA CRUZ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(89, '	ROGERO ALVES DE SOUZA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(90, '	ROSILAN DIONÍSIO SANTOS SILVA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(91, '	SABOR MINEIRO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(92, '	SANDRA CRISTINA RIBEIRO TONON', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(93, 'SERGIO BOGAZ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(94, '	SOLANGE BEZERRA DA CRUZ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(95, 'SPE TRANSPORTE E LOCAÇÃO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(96, 'SUPERMERCADO CRUZEIRO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(97, 'SUPERMERCADO NEVES ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(98, 'TIAGO SILVA DE SOUZA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(99, '	TRANSPORTES SILVA E PELOSI', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(100, 'TRATORNAVES', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(101, 'UNIÃO ALUGUEIS DE MAQUINAS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(102, '	VAGNER DOS REIS EUZEBIO TORRES', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(103, '	VALDINEY DA SILVA GOMES', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(104, '	VALDIR', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(105, 'VALDIR FAGUNDES', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(106, '	VHGC EMPREENDIMENTOS AGROPECUARIOS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(107, '	VISUAL BOX E TOLDOS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(108, 'VM TERRAPLANAGEM - ME', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(109, '	WANDERLEI DA SILVA BONIFACIO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(110, '	WASHINGTON FARIAS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(111, 'WEVERTON BATISTA DAS NEVES', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(112, '	WILLIAM DOS SANTOS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(113, 'WILLIAM ROBERTO GONÇALVES', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(114, '	A. C. FERREIRA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(115, 'ADALMIR IMADA - MIZÃO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(116, 'FABIANA BARROSO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(117, 'PAULO SERGIO FERREIRA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(118, 'TIAGO RIBEIRO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(119, 'RICARDO MOISES DA SILVA ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(120, 'JOSE APARECIDO FERNANDES', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(121, 'FERNANDO JOSE DE SOUZA FONTES  FERNANDINHO ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(122, 'RAFAEL ANTONIO MOISES', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(123, 'ADRIANO PERPETUO PEREIRA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(124, 'WAGNER STEFANO TEIXEIRA RONDA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(125, 'ANDRIEL SANTOS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(126, 'EDUARDO MARTINS JIORJUTI\r\n', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(127, 'CLAUDINEI MOREIRA DA SILVA\r\n ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(128, 'JULIO CESAR TOLENTINO - CEDRAL', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(129, 'JOSE OSVALDO MAIA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(130, 'FAZENDA BOM RETIRO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(131, 'PAV SERV', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(132, 'DALIANA COLANJO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(133, 'PAULA CRISTINA COLANJO\r\n', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(134, 'ALINE ROTTA\r\n', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(135, 'junior da jane\r\n', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(136, 'FRANCISCO MARQUES( CHICÃO ICEM)\r\n', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(137, 'LUCAS HENRIQUE SCHUMA MARTINELLI\r\n', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(138, 'MARCOS CEZAR RODRIGUES\r\n MARCÃO RAVAZZI ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(139, 'RAFAEL SCHUMA ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(140, 'WILSON ANDRELLA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(141, 'PAULO  SERAPILHA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(142, 'REGINALDO CARNEIRO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(143, 'REGINALDO MIQUELIN', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(144, 'ANDRELLA SERVIÇOS AGRICOLA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(145, 'JOSÉ FLORENCIO - PALESTINA ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(146, 'LUCIANO STORE', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(147, 'LUCIANA SANTOS CHAGAS ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(148, 'JOÃO SALES LIMA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(149, 'ROGER PEREIRA PAULINO DIAS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(150, 'ILTON BATISTA DA SILVA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(151, 'MARCOS FELIPE JUNIO RIBAS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(152, 'DAYANE MICHELE LOUREIRO DE BACHI', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(153, 'ADRIAN GONÇALVES MONTEIRO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(154, 'MARCOS VINICIUS SANTOS SANCHEZ\r\n', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(155, 'PEDRO HENRIQUE DOS SANTOS ROCHA\r\n', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(156, 'FERNANDO ROBERTO MUNIZ\r\n', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(157, 'GRISOLINO SERVIÇOS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(158, 'PEDRO COTTA ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(159, 'MICHEL GERMANI', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(160, 'CASTSEG RIO PRETO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(161, 'CASTSEG FRANQUEADOS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(162, 'CASA DE GARÇA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(163, 'DIVA BATISTA ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(164, 'MBS LOGISTICA E TRANSPORTE', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(165, 'mariana junqueira - shopping', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(166, 'VALTER ROSSI', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(167, 'WISSAN MUSSI', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(168, 'FERNANDO RODRIGO GIACOMETTI', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(169, 'AGRO CASTILHO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(170, 'MARCELO DO CISCO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(171, 'JULIO CESAR TOLENTINO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(172, 'BALIEIRO & BRANCO SERV. jonivaldo', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(173, 'VALTER ROBERTOALVES DE MELO JUNIOR', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(174, 'JOAO VICTOR - GLEIDIANE', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(175, 'ELIO ANDRADE TERRA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(176, 'MARCELO APOLINARIO DAIA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(177, 'DANILO ALVES LOUREIRO DE BACHI', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(178, 'CLAUDETE TORREZIN VILELA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(179, 'TELSITE SOLUTIONS LTDA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(180, 'RAFAELA MANICURE', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(181, 'FELIPE ROBERTO FERRARI', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(182, 'FABIO EDUARDO PEREIRA MENEZES', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(183, 'IASSIM AGRICOLA E TRANSPOTES', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(184, 'VENDAS DE PEÇAS GOL', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(185, 'MARCIO GONÇALVES - AMERICANA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(186, 'NERIO LUIS CROVINEL', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(187, 'JOSE HENRIQUE FABRI', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(188, 'TIAGO LUCAS DOS SANTOS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(189, 'ADALMOR IMADA  ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(190, 'TURISMO MENDONÇA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(191, 'AMAURY DOS REIS - FRONTEIRA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(192, 'WAGNER GUIDI - FRONTEIRA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(193, 'JULIO GUIDI -  FRONTEIRA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(194, 'ANA PAULA ZANANDREIA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(195, 'JULIO CESAR ZACANQUAQUIO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(196, '    CAIO JOSÉ SOUZA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(197, 'MARCIO CASTILHO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(198, 'SERGIO ANATRIELLO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(199, 'ELETRIFICAÇÃO GRANADA LTDA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(200, 'JAAVA TRANSPORTES', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(201, 'DELIBERTI SERVIÇOS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(202, 'JOSE JOAQUIM BONNI', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(203, 'NIELTON FERNANDO ROCHA ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(204, 'LUIS EDUARDO PREVIATTO GOMES', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(205, 'LUIZ FELIPE SIQUEIRA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(206, 'FABIO CRISTIANO DIAS - RP ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(207, 'MARIANA SILVA BIANCO DAS CHAGAS - RP', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(208, 'GLAUCIO VILCHES CAPRIO - VOTUPORANGA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(209, 'LUCIANO RODRIGUES CASTRO - AP. DE MINAS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(210, 'AMID TADEU CHARABIDINE', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(211, 'EVO TRUCK', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(212, 'VALDINEI BIL DOS SANTOS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(213, 'CARLOS ROBERTO DA SILVA MAIA - RP', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(214, 'TACIANO - SEVERINIA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(215, 'CLAUDIO ALMEIDA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(216, 'IMPACTO FRUTAL', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(217, 'LEANDRO TRINDADE', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(218, 'JOÃO PAULO LOPES DE OLIVEIRA ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(219, 'ANTONIO CARLOS FUENTES', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(220, 'CRA SERVIÇOS AGRICOLA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(221, 'COMER. FRUTAS NSA SHRA APARECIDA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(222, 'WILSON SOSSOLOTE', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(223, 'IUNES MUSSI', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(224, 'ROBERTA C. F. COSTA SOUZA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(225, 'ANTONIO MARCOS MARTINS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(226, 'AGILE COMERCIO DE PEÇAS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(227, 'LUCIANO BELEZINI ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(228, 'MARCO ANTONIO ROCHA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(229, 'REYS INDUSTRIA E SERVIÇOS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(230, 'REINALDO DOS SANTOS MEIRA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(231, 'MANUEL QUINTERO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(232, 'ELETRIFICAÇÃO RIBEIRO ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(233, 'TERRA & AREIA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(234, 'GIOVANA BORGES - EVO TRUCK', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(235, 'ADILSON DANTAS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(236, 'EZEQUIAS GLAUCO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(237, 'ALDO DEO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(238, 'RODRIGO - REVELLES', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(239, 'AGRO CHEYENNE', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(240, 'MARCO ANTONIO DE SOUZA C.F CAMPO FLORIDO ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(241, 'JK - ASSOCIAÇÃO DE PROTEÇÃO VEICULAR', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(242, 'TRUCK FORT - UBERLANDIA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(243, 'CASTANHA LTDA - SANDRO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(244, 'ALA TRANSPORTES', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(245, 'ARLINDO LOPES ala transporte ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(246, 'VALDECIR APARECIDO FERREIRA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(247, 'GLEYDSON DIAS CRUZ MOTO VIZINHO ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(248, 'EDER ALAN VICENTE', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(249, 'JOÃO CARLOS DA SILVA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(250, 'AGROCHEYNNE - PINHALZINHO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(251, 'MAURILIO SABINO DA COSTA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(252, 'JOSE MILHIM', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(253, 'ISAC ALERRANDRO DOIMO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(254, 'MARCOS SOARES DOIMO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(255, 'MAGDIEL PELEGRIN LTDA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(256, 'SEVERIANO ROGERIO SALVADOR', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(257, 'CLAUDIO ANTONIO BAPTISTA DE SOUZA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(258, 'AMARILDO JOARES DOIMO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(259, 'MARCELO ZANATA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(260, 'JOAO BERMAL', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(261, 'JOÃO CARLOS DA SILVA  (MOTO MARIA EDU.) ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(262, 'BANCO DO BRASIL', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(263, 'WALLICE PEREIRA DA SILVA - fernando eletrica', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(264, 'EVARILDO CROCCO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(265, 'JESUS ROMÃO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(266, 'DEODATO OLIVEIRA - KM 27', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(267, 'ROSA FAGUNDES DOS SANTOS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(268, 'DORIVAL SANCHES YANES', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(269, 'LUZ CARLOS DE SOUZA LIMA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(270, 'MARILDA DONIZETE G FONTES - SUCO HAWAI ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(271, 'CLEBER HIDALDO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(272, 'JAMILDO RIBEIRO DE SOUZA - CAMPO FLORIDO ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(273, 'ANTONIO SASS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(274, 'BRUNO MOREIRA DE SOUZA- TANABI', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(275, 'DIMAS TADEU DE OLIVEIRA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(276, 'WILLIAN SOSSOLOTE', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(277, 'REINALDO DE OLIVEIRA RP', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(278, 'ALAN CASSIANO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(279, 'VALDECIR ARAÚJO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(280, 'V.R. TRUCK', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(281, 'ROSINÉIA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(282, 'ALEXANDRE JOSE DA SILVA MALONI', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(283, 'LUIS BITTECUR - FRONTEIRA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(284, 'WILSON GONZAGA JIORJUTE', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(285, 'JVD TRANSPORTE E SERVIÇOS - DEO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(286, 'ALAN CASSIANO -SATELITAL', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(287, 'A. ARAUJO - SATELITAL ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(288, 'ANGOTI HIRATA - SATELITAL', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(289, 'ROSINEIA DA SILVA HIRATA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(290, 'AGRODORETO', 'J', '', '', 'S', '', '', '', '', '', '', '', NULL),
	(291, 'VALTER ROMÃO - ONDA VERDE', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(292, 'adriano amid ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(293, 'FERNANDO JESUS PEREIRA - GUARACI ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(294, 'VICTOR FIGUEIREDO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(295, 'THD TRANSPORTES', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(296, 'RUITEBRAN DE SOUZA CARVALHO ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(297, 'TIAGO GOGERIO DOS SANTOS', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(298, 'JOSE CARLOS GONÇALVES LEITE - IPIGUA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(299, 'REGIS CARLO GONÃ‡ALVES -  RIBEIRÃƒO PRETO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(300, 'ABBAS CHARAFIBIDINE', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(301, 'ANTONIO PESCONI M. EUZEBIO- RIO PRETO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(302, 'GEANDRO POMPEO - J. BONIFACIO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(303, 'GEORGE ELIAS BAPTISTA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(304, 'ISRAEL MENDES - RIBEIRÃO PRETO', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(305, 'ADRIANO AP. CREPALDI - RIO PRETO ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(306, 'LUIS PUBLIO  ', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(307, 'ANTONIO A. ANDRADE E SILVA - UBERABA', 'F', '', '', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 'N', NULL),
	(308, 'Yan Caue Manuel Baptista de souza ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 1),
	(309, 'FORNECEDOR2 ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 23),
	(310, 'FULLTIME  ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 24),
	(311, 'DUSSPY', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 25),
	(312, 'POSTO VICINAL', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 26),
	(313, 'SUPERMERCADO NEVES', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 27),
	(314, 'SUPERMERCADO POPULAR', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 28),
	(315, 'SUPERMERCADO CRUZEIRO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 29),
	(316, 'META TELECOM', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 30),
	(317, 'UNIRP', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 31),
	(318, 'DETRAN ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 32),
	(319, 'MARIANA BOGAS- CARTEIRAS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 33),
	(320, 'LANCHONETE CENTRAL', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 34),
	(321, 'MARCIA CABELEREIRA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 35),
	(322, 'PRODUTOS GLOBO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 36),
	(323, 'LOJA DO MECANICO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 37),
	(324, 'CPFL', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 38),
	(325, 'SABESP', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 39),
	(326, 'STC DO BRASIL', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 40),
	(327, 'GURTAN', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 41),
	(328, 'MARIANA BATISTA ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 42),
	(329, 'IVA DA MATTA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 43),
	(330, 'JM INSTALAÇOES', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 44),
	(331, 'LOCAL WEB ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 45),
	(332, 'MSN CONTABILIDADE', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 46),
	(333, 'BRUNO SILVA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 47),
	(334, 'CLARO S.A.', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 48),
	(335, 'COLEGIO DINAMICA OBJETIVO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 49),
	(336, 'ALICE APARECIDA DA SILVA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 50),
	(337, 'SOSSOLOTE TRANSPORTE', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 51),
	(338, 'INSS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 52),
	(339, 'PREFEITURA MUNICIPAL DE GARÇA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 53),
	(340, 'INES SANTANA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 54),
	(341, 'UNIMED', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 55),
	(342, 'CONSORCIO TARRAF', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 56),
	(343, 'OQUEI PROVEDOR DE INTERNET', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 57),
	(344, 'NETFLIX', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 58),
	(345, 'GRANPEL ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 59),
	(346, 'MARINA JUNQUEIRA- SHOPPING', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 60),
	(347, 'MORENA BELA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 61),
	(348, 'PAO DE AÇUCAR', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 62),
	(349, 'JOICE TEIXEIRA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 63),
	(350, 'SUPERMERCADO MUFFATO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 64),
	(351, 'BANCO DO BRASIL ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 65),
	(352, 'MAGAZINE ELIZ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 66),
	(353, 'ATACADAO DOS CALÇADOS ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 67),
	(354, 'MAGAZINE LUIZA ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 68),
	(355, 'AVS MODA ÍNTIMA  ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 69),
	(356, 'LUIZ FELIPE EMPRES. LIMPEZA DE CHÃO ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 70),
	(357, 'CRUZ DE PRATA LABORATÓRIO ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 71),
	(358, 'GUERINO SEISSENTO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 72),
	(359, 'PADARIA DA DONA MARIA ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 73),
	(360, 'DROGARIA POUPA AQUI', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 74),
	(361, 'ACADEMIA STYLLUS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 75),
	(362, 'CASAS BAHIA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 76),
	(363, 'CIDINHA CATALAGO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 77),
	(364, 'EDUARDA ARMIATO MASSAGENS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 78),
	(365, 'DAS - SIMPLES NACIONAL', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 79),
	(366, 'JACOB SALVIANO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 80),
	(367, 'JOAO SANTANA - ADV', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 81),
	(368, 'RIO TUDOR BATERIAS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 82),
	(369, 'MISTER BURGUER - MARQUETE', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 83),
	(370, 'PADARIA NOVA UNIÃO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 84),
	(371, 'AÇAI MANIA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 85),
	(372, 'MERCEARIA PAVANI', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 86),
	(373, 'POSTO IPIRANGA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 87),
	(374, 'PIZZARIA MASSA FINA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 88),
	(375, 'CORREIOS S.A.', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 89),
	(376, 'MOLECAGIOO PIZZARIA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 90),
	(377, 'SAU RESTAURANTE', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 91),
	(378, 'BURGUER KING', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 92),
	(379, 'PEDAGIO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 93),
	(380, 'KALUNGA LIVRARIA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 94),
	(381, 'BOTICARIO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 95),
	(382, 'FEIRA LIVRE NOVA GRANADA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 96),
	(383, 'PANICHE MODAS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 97),
	(384, 'POSTO TABOCAO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 98),
	(385, 'JAPONES RESTAURANTE', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 99),
	(386, 'PONTO DO SALGADO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 100),
	(387, 'PARIS EVENTOS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 101),
	(388, 'JJ CALÇADOS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 102),
	(389, 'BARBARA DANTAS  - DOCES', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 103),
	(390, 'CBT INFORMATICA ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 104),
	(391, 'SIDNEI ZANATA- JAPONES', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 105),
	(392, 'PIU MAR LANCHES', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 106),
	(393, 'KOPENHAGEN - RIO PRETO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 107),
	(394, 'CARREFOUR', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 108),
	(395, 'RESTAURANTE SHOPPING', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 109),
	(396, 'CIA DA BOLSA ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 110),
	(397, 'LEANDRO ASSADOS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 111),
	(398, 'CINEMA RIO PRETO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 112),
	(399, 'SABWAY', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 113),
	(400, 'PIRES GAS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 114),
	(401, 'MARCIA CABELEREIRA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 115),
	(402, 'BRUNO VICENTE', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 116),
	(403, 'FARMACIA DEO FARMA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 117),
	(404, 'SERGIO BOGAS JUNIOR', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 118),
	(405, 'FARMACIA TOTAL ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 119),
	(406, 'CACHORRO QUENTE DO LUCAS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 120),
	(407, 'SERGIO LUIS VIEIRA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 121),
	(408, 'CASA DO AÇAI', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 122),
	(409, 'SPOTIFY', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 123),
	(410, 'LUANA FAGUNDES', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 124),
	(411, 'CARRODO OVO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 125),
	(412, 'BIANCHI SERVE FESTA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 126),
	(413, 'VALTER ROSSI - PEÇAS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 127),
	(414, 'PÃES GRANADA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 128),
	(415, 'RESTAURANTE RECHES', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 129),
	(416, 'GUILHERME D`AGOSTINO ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 130),
	(417, 'GRANPEL EMBALAGENS ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 131),
	(418, 'SHOPING DA UTILIDADE S.J. RIO PRETO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 132),
	(419, 'DROGARIA VIDA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 133),
	(420, 'MIRIAN FLORES GUAPIAÇU', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 134),
	(421, 'MINIMERCADO MARTINS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 135),
	(422, 'FINA ESTAMPA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 136),
	(423, 'SHOPEE', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 137),
	(424, 'NEXT CALÇADOS RIO PRETO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 138),
	(425, 'PRIMEIRA CLASS RIO PRETO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 139),
	(426, 'MAGRAS SÃO JOSE DO RIO PRETO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 140),
	(427, 'DIJO AUTO PEÇAS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 141),
	(428, 'JORGE ELETRIFICAÇÃO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 142),
	(429, 'BEACH PARK WORD', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 143),
	(430, 'FARMÁCIA DO ELISEU', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 144),
	(431, 'DALILA DOCERIA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 145),
	(432, 'AUTONOMO NOVA GRANADA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 146),
	(433, 'LOJAS LIVIA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 147),
	(434, 'BAILES E FESTAS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 148),
	(435, 'SORVETERIA CREMOSO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 149),
	(436, 'RAFAELA MANICURE', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 150),
	(437, 'CARTUCHOS .COM', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 151),
	(438, 'AGROPECUÁRIA ALVORADA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 152),
	(439, 'GLAUCIA CALANGO VALVIT', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 153),
	(440, 'ANA JULIA BATISTA DE SOUZA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 154),
	(441, 'POSTO RIO PRETO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 155),
	(442, 'ELENILDO PROPAGANDA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 156),
	(443, 'ELIAS SAMPAIO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 157),
	(444, 'POSTO SERTANEJO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 158),
	(445, 'JOSE APARECIDO FERNANDES (CIDINHO)', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 159),
	(446, 'ATACADÃO R.P ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 160),
	(447, 'shopbyik by ik', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 161),
	(448, 'VISUAL BOX', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 162),
	(449, 'EMPORIO NATULAR ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 163),
	(450, 'UBER', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 164),
	(451, '12 PO 8 LANCHONETE', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 165),
	(452, 'FORMES FORMATURAS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 166),
	(453, 'ANTONELLI INFORMÁTICA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 167),
	(454, 'REIKE', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 168),
	(455, 'D\'ANGUS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 169),
	(456, 'PESQUEIRO MARELI', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 170),
	(457, 'FLESH CELL', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 171),
	(458, 'ELAINE ANTONIELLI', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 172),
	(459, 'LENADRO AR CONDICIONADO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 173),
	(460, 'LUCIA FAGUNDES DOS SANTOS COSTUREIRA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 174),
	(461, 'MANUELA ARMIATO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 175),
	(462, 'SHEN IMPORTADOS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 176),
	(463, 'SUPERMERCADO A&D', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 177),
	(464, 'LOJA PETUTI', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 178),
	(465, 'MINI MERCADO FERRARI', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 179),
	(466, 'POSTO COMIM', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 180),
	(467, 'RODEIO CLUBE DOS 40', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 181),
	(468, 'LOJA MISS LADY SHOOPING RIO PRETO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 182),
	(469, 'DENILSON CABELEREIRO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 183),
	(470, 'CARIOCA SALGADO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 184),
	(471, 'CLAUDIA ROBERTA BATISTA DE SOUZA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 185),
	(472, 'LA NOSTRA PIZZARIA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 186),
	(473, 'JOHNATAN DA SILVA LIMA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 187),
	(474, 'FARMÃCIA DE MANIPULAÃ‡ÃƒO QUINTAESSENCIA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 188),
	(475, 'DANILO ESPETO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 189),
	(476, 'CHURRASCARIA BOI BOM ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 190),
	(477, 'EVENTOS RIO PRETO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 191),
	(478, 'CRIS COSMETICOS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 192),
	(479, 'AUTO PEÇAS ROVERSI', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 193),
	(480, 'AQUARELA KIDS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 194),
	(481, 'YESSCO LOJA ROUPA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 195),
	(482, 'WJS AMORTECEDORES', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 196),
	(483, 'JOSÉ ALBERTO GOMES CANILE', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 197),
	(484, 'NOBEL ESCOLA ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 198),
	(485, 'RENATA CABELEREIRA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 199),
	(486, 'JARDIM URBANO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 200),
	(487, 'FIRST CLASS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 201),
	(488, 'VALISERE', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 202),
	(489, 'POSTO ESTRADA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 203),
	(490, 'borracharia', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 204),
	(491, 'SIRLAINE GARLHARDO HEIKE', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 205),
	(492, 'CASA DOS IDOSOS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 206),
	(493, 'LAVA JATO PRIMOS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 207),
	(494, 'ROSEVALDO SOUZA OLIVEIRA BAUN', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 208),
	(495, 'RESTAURANTE ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 209),
	(496, 'DIMAS TIAGO LOCUTOR', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 210),
	(497, 'TREVÃO RIO PRETO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 211),
	(498, 'HOTEL', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 212),
	(499, 'SAMUCA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 213),
	(500, 'TITI PAPELARIA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 214),
	(501, 'RODEIO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 215),
	(502, 'DONA BYLA CONFECÇÃO INTERNET', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 216),
	(503, 'CRISTINA FAXINEIRA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 217),
	(504, 'LUCIO SORVETES', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 218),
	(505, 'BERTACO MÓVEIS E TINTAS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 219),
	(506, 'SONDAS PESQUISE E PUBLICIDADES ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 220),
	(507, 'ELE GRANDE ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 221),
	(508, 'CONSTRUNOVA MATERIAL DE CONSTRUÇÃO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 222),
	(509, 'SOBERANA ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 223),
	(510, 'ZIGON', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 224),
	(511, 'TEDA ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 225),
	(512, 'LUNAR BRONZE', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 226),
	(513, 'B2 PNEUS LTDA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 227),
	(514, 'MR AUTO CAR CENTER', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 228),
	(515, 'SILVANA ARMIATO ESFIRRA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 229),
	(516, 'LUCIANA MATTOS ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 230),
	(517, 'SAPATARIA RIBEIRO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 231),
	(518, 'TONINHO DA LIMPEZA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 232),
	(519, 'UNI DIESEL', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 233),
	(520, 'LOBO TORNEIRO ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 234),
	(521, 'RENATO MECANICA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 235),
	(522, 'TECO\'S BAR', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 236),
	(523, 'COMPRE MIX ATACADISTA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 237),
	(524, 'NATURA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 238),
	(525, 'DAIANE CRISTIANO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 239),
	(526, 'PAULO INSTALADOR', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 240),
	(527, 'HOSPEDAGEM', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 241),
	(528, 'VENDEDOR AMBULANTE', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 242),
	(529, 'DOAÇÃO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 243),
	(530, 'BUTECO GARAGEM', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 244),
	(531, 'SUPERMENRCADO GRAN MORO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 245),
	(532, 'POSTO BOGAS ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 246),
	(533, 'LOJA ASSISTENTE DE CELULAR', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 247),
	(534, 'ALANA GOMS ERTHAL', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 248),
	(535, 'INSTALADOR EVO TRUCK', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 249),
	(536, 'FERNANDO AUTO ELETRICA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 250),
	(537, 'FLORICULTURA STYLLUS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 251),
	(538, 'ITOUCH STORE INTERNETE', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 252),
	(539, 'ENEM', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 253),
	(540, 'GILSON', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 254),
	(541, 'GRAN BEACH', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 255),
	(542, 'CACAU SHOW', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 256),
	(543, 'DOGDE AMERICAN BAR', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 257),
	(544, 'RASTREMAIS GUARIBA DOUGLAS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 258),
	(545, 'ELETRIFICAÇÃO GRANADA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 259),
	(546, 'CLAUDIA SOLEMAM', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 260),
	(547, 'DR. ZEN INTERNET', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 261),
	(548, 'REI DA PIZZA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 262),
	(549, 'MARCIO ODINEI DEHEIN', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 263),
	(550, 'LOJAS CENTER CASA ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 264),
	(551, 'DR. MARCELO ABRÃO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 265),
	(552, 'GRAN AR', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 266),
	(553, 'ISABELA GALANTE', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 267),
	(554, 'GABRIELA ROBERTA MAQUIAGEM', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 268),
	(555, 'JACARÉ MOTO PEÇAS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 269),
	(556, 'JACARÉ MOTO PEÇAS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 270),
	(557, 'CHURRASCARIA CATENA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 271),
	(558, 'CELSINHO GÁS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 272),
	(559, 'TELTONIKA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 273),
	(560, 'SAÚDE CAP ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 274),
	(561, 'GRAFICA SÃO BENEDITO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 275),
	(562, 'BAIDE LOJA INTERNET', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 276),
	(563, 'INSTALADOR TRUK FORT', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 277),
	(564, 'UNIAR AR CONDICIONADO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 278),
	(565, 'AUTO ELETRICA ALAN FELIX', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 279),
	(566, 'PAULO ALVES DA CUNHA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 280),
	(567, 'MIDEA BANNER', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 281),
	(568, 'FRITA SELA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 282),
	(569, 'PATROCINIO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 283),
	(570, 'ZZ LOJA PRAÇA SHOOPING', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 284),
	(571, 'ELEN CRISTINA ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 285),
	(572, 'SANTA LOLA CALÇADOS ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 286),
	(573, 'CIRCO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 287),
	(574, 'SROVETÃO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 288),
	(575, 'MATHEUS OLIVEIRA DE PAULA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 289),
	(576, 'POSTO FÉRIAS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 290),
	(577, 'FERIAS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 291),
	(578, 'LOJAS PEROLA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 292),
	(579, 'JOÃO PAULO LOPES ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 293),
	(580, 'PREFEITURA MUNICIPAL DE NOVA GRANADA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 294),
	(581, 'LARISSA FRANÇA MALAVASI', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 295),
	(582, 'JF AUTO ELETRICA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 296),
	(583, 'PEDAGIO FÉRIAS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 297),
	(584, 'domésticas em experiencia', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 298),
	(585, 'ARMAZÉM CHOPERIA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 299),
	(586, 'ARMAZÉM CHOPERIA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 300),
	(587, 'RML CONFECÇÕES (ROBERTA)', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 301),
	(588, 'WIPINK', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 302),
	(589, 'sabor das casa restauranrte', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 303),
	(590, 'ELETROZEMA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 304),
	(591, 'IMOBILIÃRIA INVEST IMÃ“VEIS GARÃ‡A', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 305),
	(592, 'LICENCIAMENTO DE VEÍCULOS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 306),
	(593, 'ALUGUEL DE TRAJES ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 307),
	(594, 'Joyce cruz', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 308),
	(595, 'Rafael Mangas BArbeiro', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 309),
	(596, 'eletrozema', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 310),
	(597, 'LOJA FIDELIS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 311),
	(598, 'DATATEM', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 312),
	(599, 'DIOMINIO JOSE DA SILVA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 313),
	(600, 'BARRACÃƒO MATERIAL DE CONSTRUÃ‡ÃƒO ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 314),
	(601, 'OTICA RENASCER', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 315),
	(602, 'FACULDADE BARÃO DE MAUÁ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 316),
	(603, 'Kamila manicure', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 317),
	(604, 'agromera produtos agropecuária', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 318),
	(605, 'peixada do wilso', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 319),
	(606, 'MERCADO LIVRE', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 320),
	(607, 'WILIAN FERNANDES SILVA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 321),
	(608, 'Amarok', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 322),
	(609, 'tania dos Santos Affonso', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 323),
	(610, 'canva', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 324),
	(611, 'guincho', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 325),
	(612, 'café com flores', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 326),
	(613, 'PEDRO GERALDO MAGO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 327),
	(614, 'ME LINDA COSMÉTICOS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 328),
	(615, 'MC DONALD', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 329),
	(616, 'TIMBORÉ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 330),
	(617, 'CLAUDIO ANTONIO BAPTISTA DE SOUZA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 331),
	(618, 'INSTALADOR ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 332),
	(619, 'CRISTIANE MILHARI ALVES DE SOUZA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 333),
	(620, 'SHOOPING GRANADENSE ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 334),
	(621, 'TEM MAIS UTILIDADES NOVA GRANADA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 335),
	(622, 'RSISTEN RENATO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 336),
	(623, 'CALDEIRÃO LANCHES', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 337),
	(624, 'NIVAS CAMISARIA RIO PRETO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 338),
	(625, 'AMÉRICA PNEUS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 339),
	(626, 'ESTACIONAMENTO ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 340),
	(627, 'natura', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 341),
	(628, 'ADALTO PRADO INSTALADOR', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 342),
	(629, 'SABINO TURBINAS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 343),
	(630, 'DHOW LAVA JATO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 344),
	(631, 'DOM THEO ASSADOS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 345),
	(632, 'ALUGUEL ANA JULIA RIBEIRÃO PRETO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 346),
	(633, 'FAXINEIRA RIBEIRÃO PRETO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 347),
	(634, 'MONIRIK', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 348),
	(635, 'LAZER DIVERSOS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 349),
	(636, 'HOTEL ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 350),
	(637, 'AGROVIA CASA AGROPECUÁRIA', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 351),
	(638, 'DROGA RAIA ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 352),
	(639, 'RAFAEL OLIVEIRA INSTALADOR NG', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 353),
	(640, 'THEO FELIPE  ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 354),
	(641, 'viga máquinas ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 355),
	(642, 'suco hawai', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 356),
	(643, 'Oficina de amortecedor ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 357),
	(644, 'Gustavo souza ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 358),
	(645, 'THERMAS DE OLIMPIA ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 359),
	(646, 'PASTELARIA LIKES RIO PRETO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 360),
	(647, 'CINE BABY', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 361),
	(648, 'GRAN AR NOVA GRANADA ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 362),
	(649, 'SAVEGNAGO RIBEIRÃO PRETO', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 363),
	(650, 'MARAVILHAS DO LAR ', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 364),
	(651, 'LOJAS PERNAMBUCANAS', 'J', '', '', 'N', 'S', 'N', 'N', 'N', 'N', 'N', 'N', 365),
	(652, 'Teste Fornecedor 001', 'J', '', '', '', 'S', '', '', '', '', '', '', NULL),
	(654, 'teste fonecedor 002', 'J', '', '', '', 'S', '', '', '', '', '', '', NULL),
	(655, 'gabriel pinheiro fernandes', 'J', '', '', '', 'S', '', '', '', '', '', '', NULL),
	(656, 'COLABORADOR 025', 'F', '', '', '', '', 'S', '', '', '', '', '', NULL),
	(657, 'DUARTE CASQUINHA', 'F', '', '', 'S', '', '', '', '', '', '', '', NULL),
	(659, 'MARCIO JOSE BARROS PEREIRA', 'F', '', '', 'S', '', '', '', '', '', '', '', NULL),
	(661, 'Convenio 001', 'F', '', '', '', '', '', 'S', '', '', '', '', NULL),
	(662, 'jorge o contador', 'J', '', '', '', '', '', '', 'S', '', '', '', NULL),
	(663, 'PESSOA 001 ', 'F', 'PINTOPLAYS.COM.BR', 'WWW.COM.BR', '', '', 'S', '', '', '', '', '', NULL),
	(664, 'PESSOA 002', 'J', 'TWITCH.TV@GMAIL.COM', 'WWW.TWITCH.TV.COM.BR', '', 'S', '', '', '', '', '', '', NULL),
	(665, 'PESSOA 003', 'J', '', '', '', '', '', '', 'S', '', '', '', NULL),
	(666, 'pipoca doce mt docinha hhhhhhm....', 'J', '', '', '', '', '', '', '', 'S', '', '', NULL),
	(667, 'pipoquinha com brigadeiroseria uma boa (faz pipoca terceirizadamente)', 'J', '', '', '', '', '', '', '', '', 'S', '', NULL),
	(668, 'teste responsavel socio ', 'J', 'aisygdsaduahs', 'kadahiduidahsd', '', '', '', '', '', '', '', 'S', NULL),
	(669, 'llllllllllllllllllllll', 'F', 'llllllll', 'llllllllllll', '', '', '', '', '', '', '', 'S', NULL),
	(670, 'João Silva', 'F', 'joao.silva@example.com', 'www.joaosilva.com', '', '', '', '', '', 'S', '', '', NULL),
	(671, 'Maria Oliveira', 'F', 'maria.oliveira@example.com', 'www.mariaoliveira.com', '', '', '', '', '', 'S', '', '', NULL),
	(672, 'Cliente roberto vieira alves', 'J', '', '', 'S', '', '', '', '', '', '', '', NULL),
	(673, 'PROFESSOR LINGUICA', 'F', '', '', '', '', '', '', 'S', '', '', '', NULL),
	(674, 'abacate', 'J', '', '', '', '', '', '', 'S', '', '', '', NULL),
	(675, '123', 'F', '123', '123', '', '', 'S', '', '', '', '', '', NULL),
	(676, 'ttttt', 'J', 'tttt', 'tttt', '', '', '', '', '', '', 'S', '', NULL);

-- Copiando estrutura para tabela teste_grupo_mbs.responsavel_socio
CREATE TABLE IF NOT EXISTS `responsavel_socio` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PESSOA` int(11) NOT NULL,
  `ID_CONTABIL_CONTA` int(11) DEFAULT NULL,
  `FONE` varchar(13) DEFAULT NULL,
  `FAX` varchar(14) DEFAULT NULL,
  `LOGRADOURO` varchar(100) DEFAULT NULL,
  `NUMERO` varchar(10) DEFAULT NULL,
  `COMPLEMENTO` varchar(100) DEFAULT NULL,
  `BAIRRO` varchar(60) DEFAULT NULL,
  `CEP` varchar(8) DEFAULT NULL,
  `MUNICIPIO_IBGE` int(11) DEFAULT NULL,
  `UF` char(2) DEFAULT NULL,
  `EMAIL` varchar(250) DEFAULT NULL,
  `PIS_NIT` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CTA_CONTAB_SOCIO` (`ID_CONTABIL_CONTA`),
  KEY `FK_PESSOA_SOCIO` (`ID_PESSOA`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_swedish_ci PACK_KEYS=0 COMMENT='Armazena os dados do responsável legal pela empresa. ';

-- Copiando dados para a tabela teste_grupo_mbs.responsavel_socio: ~2 rows (aproximadamente)
INSERT INTO `responsavel_socio` (`ID`, `ID_PESSOA`, `ID_CONTABIL_CONTA`, `FONE`, `FAX`, `LOGRADOURO`, `NUMERO`, `COMPLEMENTO`, `BAIRRO`, `CEP`, `MUNICIPIO_IBGE`, `UF`, `EMAIL`, `PIS_NIT`) VALUES
	(1, 668, 7, '3', '131313', '1313', '3', '313123', '131', '1231321', 2313, 'AL', '1231', 313),
	(2, 669, 7, '9999999999', '99999', '99999', '9999999999', '9999999999999999999999', '9999999', '0999', 1215752191, 'AP', '99999999', 1215752191);

-- Copiando estrutura para tabela teste_grupo_mbs.sindicato
CREATE TABLE IF NOT EXISTS `sindicato` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PESSOA` int(11) NOT NULL,
  `ID_CONTABIL_CONTA` int(11) DEFAULT NULL,
  `CODIGO_BANCO` int(11) DEFAULT NULL,
  `CODIGO_AGENCIA` int(11) DEFAULT NULL,
  `CONTA_BANCO` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin DEFAULT NULL,
  `CODIGO_CEDENTE` varchar(30) DEFAULT NULL,
  `LOGRADOURO` varchar(100) DEFAULT NULL,
  `NUMERO` varchar(10) DEFAULT NULL,
  `BAIRRO` varchar(100) DEFAULT NULL,
  `MUNICIPIO_IBGE` int(11) DEFAULT NULL,
  `UF` char(2) DEFAULT NULL,
  `FONE1` varchar(14) DEFAULT NULL,
  `FONE2` varchar(14) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `TIPO_SINDICATO` char(1) DEFAULT NULL COMMENT 'P=patronal, E=empregados',
  `DATA_BASE` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CTA_CONTAB_SINDICATO` (`ID_CONTABIL_CONTA`),
  KEY `FK_PESSOA_SINDICATO` (`ID_PESSOA`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_swedish_ci PACK_KEYS=0 COMMENT='Tabela das sindicatos patronais';

-- Copiando dados para a tabela teste_grupo_mbs.sindicato: ~0 rows (aproximadamente)
INSERT INTO `sindicato` (`ID`, `ID_PESSOA`, `ID_CONTABIL_CONTA`, `CODIGO_BANCO`, `CODIGO_AGENCIA`, `CONTA_BANCO`, `CODIGO_CEDENTE`, `LOGRADOURO`, `NUMERO`, `BAIRRO`, `MUNICIPIO_IBGE`, `UF`, `FONE1`, `FONE2`, `EMAIL`, `TIPO_SINDICATO`, `DATA_BASE`) VALUES
	(1, 14, 7, 123, 213123, '1231', '123', '', '', '', NULL, '', '', '', '', '', '2024-06-06');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
